apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-dpl
  labels:
    app: will-dpl
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will-pod
  template:
    metadata:
      labels:
        app: will-pod
    spec:
      containers:
      - name: will-cnt
        image: wil42/playground:v1
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: will-svc
  namespace: dev
  labels:
    app: will-svc
spec:
  type: LoadBalancer
  selector:
    app: will-pod
  ports:
    - port: 8081
      targetPort: 8081
