# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "etachottS" do |machine1|
    machine1.vm.box = "generic/alpine319"
    machine1.vm.hostname = "etachottS"
    machine1.vm.network "private_network", ip: "192.168.56.110", auto_config: false

    machine1.vm.provision "shell", run: "always", inline: "ifconfig eth1 192.168.56.110 netmask 255.255.255.0 up"

    machine1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.customize ["modifyvm", :id, "--name", "etachottS"]
      vb.cpus = 1
      vb.name = "etachottS"
      vb.gui = false
    end

    machine1.vm.provision "shell" do |s|
      s.path = "script.sh"
      s.args = "etachottS"
    end
  end

  config.vm.define "etachottSW" do |machine2|
    machine2.vm.box = "generic/alpine319"
    machine2.vm.hostname = "etachottSW"
    machine2.vm.network "private_network", ip: "192.168.56.111", auto_config: false

    machine2.vm.provision "shell", run: "always", inline: "ifconfig eth1 192.168.56.111 netmask 255.255.255.0 up"

    machine2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.customize ["modifyvm", :id, "--name", "etachottSW"]
      vb.cpus = 1
      vb.name = "etachottSW"
      vb.gui = false
    end

    machine2.vm.provision "shell" do |s|
      s.path = "script.sh"
      s.args = "etachottSW"
    end
  end
end
